name: Generate contribution snake

on:
  schedule:
    - cron: "15 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: contribution-snake
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate SVG files
        uses: Platane/snk@d8f6715049803e982ee5ff501b6b9b7d5deeb09b
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish output branch
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
          commit_message: "chore: update contribution snake [skip ci]"
